services:
  baza_de_date:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: nume_user
      POSTGRES_PASSWORD: parola_user
      POSTGRES_DB: nume_baza_de_date
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  vpn-proxy:
    image: serjs/go-socks5-proxy
    environment:
      PROXY_USER: admin
      PROXY_PASSWORD: parola1109
    ports:
      - "1080:1080"

  crawler_aplicatie:
    build: .
    environment:
      TELEGRAM_TOKEN: "TOKEN_BOT_TELEGRAM"
      DATABASE_URL: "postgres://nume_user:parola_user@baza_de_date:5432/nume_baza_de_date?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - baza_de_date

volumes:
  postgres_data: